name: Java workflow

on:
  push:
    branches:
      - chrome_window_tests

env:
  NODE_VERSION: '13.x'

jobs:
  chrome_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v1
      - name: Cache Bazel artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel-disk
            ~/.cache/bazel-repo
          key: ${{ runner.os }}-bazel-chrome-tests-${{ hashFiles('**/BUILD.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-chrome-tests-
            ${{ runner.os }}-bazel-build-
      - name: Setup bazelisk
        uses: ./.github/actions/setup-bazelisk
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Setup Chrome and chromedriver
        uses: ./.github/actions/setup-chrome
      - name: Start XVFB
        run: Xvfb :99 &
      - name: Run browser tests in Chrome
        uses: ./.github/actions/bazel
        with:
          command: test //java/client/test/org/openqa/selenium:WindowTest-chrome
